projects:
  - id: locally-stored-project
    location: wonderful-project
    metrics: ALL
    files: bean
  - id: remotely-stored-project
    location: https://github.com/emaiannone/surface-test-project
    metrics: CAT,CMT,CIDA,RPB,CAIW,CCT,CDP
    revisionFilter:
      type: range
      value: ea4f388b4..803e3c896
