projects:
  - id: locally-stored-project
    location: wonderful-project
    metrics: CAT,CMT,CDP
  - id: remotely-stored-project
    location: https://github.com/emaiannone/surface-test-project
    metrics: ALL,-CCE
    classifiedPatterns: ./mypatterns.txt
    files: bean
    revisionFilter:
      type: range
      value: 4135ea1f..2f3ed97b
    branch: master